# Generated by Django 4.1.4 on 2022-12-25 22:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True)),
                ('title', models.CharField(max_length=300)),
                ('content', ckeditor.fields.RichTextField()),
                ('pub_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
